# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: advent-of-code-2018
  links:
    - url: https://adventofcode.com/2018
      title: Advent of Code 2018
      type: proposition
  tags:
    - ruby
spec:
  type: application
  lifecycle: production
  system: advent-of-code
  owner: developers
  dependencyOf:
    - component:default/advent-of-code-2019
